DROP TABLE IF EXISTS PRODUCT_DATA;
  
CREATE TABLE PRODUCT_DATA(
	id int(10)PRIMARY KEY,
	asin VARCHAR(11) NOT NULL,
  	keyword VARCHAR(100) NOT NULL,
  	rank int(4) NOT NULL,
  	timestamp int(12) NOT NULL
);




